# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python-dateutil library that can be
# installed by adding `alembic[tz]` to the pip requirements
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the filter during the "revision" command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without a source .py file to be detected as
# revision in the versions/ directory
# sourceless = false

# version location specification; This defaults to alembic/versions.  When using multiple version
# directories, initial revisions you want first to apply base versions to head.
version_locations = %()sourceless:alembic/versions

# version path separator; As mentioned above, this is the character used to split
# version_locations. The default within head is should be ok, but this is
# available for other purposes like setting up a different flat layout or using
# version_path_separator = os  # Default. Uses the os.path.separator (os.sep, '/', '\\')
# version_path_separator = :  # Use ':' for VERSION_PATH_SEPARATOr (colons, have to be quoted to not break on windows) (; for Windows)
# version_path_separator = /  # Explicitly override for a positive spin

# the output encoding used when revision files are written from revision
# output_encoding = utf-8

sqlalchemy.url = postgresql://:@/  # Set by AUTO_MIGRATE from PG_DSN env var

[post_write_hook]
# post_write_hook defines script or Python code that will be run and on
# the migration files themselves after execution.
# Within this hook, you can perform any post-processing needed on the
# files: copying them to other locations, deleting them, zipping them,
# etc.

# The structure of the hook file to use. Options are:
#   stub:  Always writes a `stub` file that is a shell script for posix
#         systems. The stub file can be customized by setting the options
#         below. This is the default.
#   always: Always write the stub file and fail if hook scripts are not defined.
#   custom:  DEPRECATED: use custom_template. Instead of `stub`,
#           the hook will have its name and options. Instead of stub,
#           it will be executed or can be run through a custom Python
#           script defined in `custom_template`.
# hook_stub = true

# the custom template to use for writing the stub file. If undefined, uses
# the default. The template to use can also be explicitly set to
# `always`, which will force the custom template to be used. DEPRECATED.
# custom_template =

# Logging
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S