apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finna-app-staging

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret-patch.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  environment: staging

images:
  - name: ghcr.io/acarmisc/finops-api
    newName: ghcr.io/acarmisc/finops-api
    newTag: staging-test
