apiVersion: v1
kind: ServiceAccount
metadata:
  name: finops-api-sa
  namespace: finna-app-staging
  annotations:
    iam.gke.io/gcp-service-account: finna-staging-sa@abs-digital-playground.iam.gserviceaccount.com