apiVersion: v1
kind: Service
metadata:
  name: finops-api
  namespace: finops
  labels:
    app: finops-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: finops-api
