apiVersion: v1
kind: Service
metadata:
  name: finna-app-ui
  labels:
    app: finna-app-ui
spec:
  type: ClusterIP
  selector:
    app: finna-app-ui
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
