module.exports = {
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.tsx?$': ['ts-jest', { useESM: false }],
  },
  testRegex: '(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/__tests__/**',
    '!src/**/__snapshots__/**',
    '!src/main.tsx',
    '!src/query/**',
    '!src/config/**',
    '!src/env.d.ts',
  ],
  setupFilesAfterEnv: ['<rootDir>/src/test/setup.ts'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/src/main.tsx',
    '/src/test/',
    '/src/query/',
    '/src/services/apiClient.ts',
  ],
  coverageProvider: 'v8',
  rootDir: '.',
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  verbose: true,
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@/components/shared$': '<rootDir>/src/__mocks__/components/shared/index.ts',
    '^@/services/apiClient$': '<rootDir>/src/__mocks__/apiClient.ts',
    '^@/contexts/ToastContext$': '<rootDir>/src/__mocks__/contexts/ToastContext.tsx',
    '^@/contexts/DateRangeContext$': '<rootDir>/src/__mocks__/contexts/DateRangeContext.tsx',
    '^@/api/hooks$': '<rootDir>/src/__mocks__/api/hooks/index.ts',
    '^@tanstack/react-query$': '<rootDir>/node_modules/@tanstack/react-query/build/legacy/index.cjs',
  },
}
