apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finops

resources:
  - ../../base

commonLabels:
  environment: prod

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: finops-api
      spec:
        replicas: 3
        template:
          spec:
            containers:
            - name: api
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "500m"
                limits:
                  memory: "512Mi"
                  cpu: "1000m"
    target:
      kind: Deployment
      name: finops-api
  - patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: finops-extractor-gcp
      spec:
        concurrencyPolicy: Replace
    target:
      kind: CronJob
      name: finops-extractor-gcp
  - patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: finops-extractor-azure
      spec:
        concurrencyPolicy: Replace
    target:
      kind: CronJob
      name: finops-extractor-azure
  - patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: finops-extractor-exchange-rates
      spec:
        concurrencyPolicy: Replace
    target:
      kind: CronJob
      name: finops-extractor-exchange-rates
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: finops-config
      data:
        ENVIRONMENT: prod
        LOG_LEVEL: WARNING
    target:
      kind: ConfigMap
      name: finops-config
